if(EXISTS "D:/binsnake/omill/build-remill2/tests/omill-ollvm-jit-tests[1]_tests.cmake")
  include("D:/binsnake/omill/build-remill2/tests/omill-ollvm-jit-tests[1]_tests.cmake")
else()
  add_test(omill-ollvm-jit-tests_NOT_BUILT omill-ollvm-jit-tests_NOT_BUILT)
endif()
